### ISSUE TITLE
Question: Beta Testing

### ISSUE THREAD

**Issue by SLO-onca** [EvgeniyKorepov/MinerPro-for-NiceHash#1]
Hi Evgeniy

I have a small farm with two rigs, expanding slowly. Very interested in your project (I was about to start my own, but came across you on the CUDA 9.1 thread)

If you were looking for a Beta tester, I would happy to be considered. I'm a Software Engineer by day, crypto miner by night...

Regardless, good luck with you project!

Shiftleft Operations

**Comment by EvgeniyKorepov** [comment]
Thank you for your interest in the project!
The main problems are eliminated - memory leaks, stability of work, reliability of push announcements on the mobile application.
Alpha release will lay out for public testing by the end of this week.

**Comment by EvgeniyKorepov** [comment]
@SLO-onca The first release has been published. Very interested in your opinion about the application.
[https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash/releases](https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash/releases)

**Comment by SLO-onca** [comment]
@EvgeniyKorepov Looking forward to installing either tonight (EST) or over the weekend.

If I see any issues, have comments or suggestions, I will be sure to let you know here.

Thanks
