### ISSUE TITLE
Benchmark for primary settings

### ISSUE THREAD

**Issue by BaGRoS** [EvgeniyKorepov/MinerPro-for-NiceHash#15]
Please add a basic check of all basic algorithms with basic settings, in order to fine-tune them later and find more precise settings. It takes a very long time to do this manually.

**Comment by EvgeniyKorepov** [comment]
The benchmark is done once and for a long time. There is no need to repeat constantly. In addition, you can change parameters during profitable mining and immediately save as a benchmark.
So far, I see no reason to add this feature.
