### ISSUE TITLE
Cant get excavator started

### ISSUE THREAD

**Issue by fouriedavid** [EvgeniyKorepov/MinerPro-for-NiceHash#17]
Hi I cant get the excavator started in stage 2 it keeps saying error, excavator not connected please help.

**Comment by EvgeniyKorepov** [comment]
Check the version of the Excavator. The version 1.5.* has a new API and it is not yet supported (it will be supported in the coming days). Use while the version of the Excavator 1.4.*

**Comment by fouriedavid** [comment]
struggling to find Excavator 1.4

**Comment by fouriedavid** [comment]
got 1.4.1 and excavator is running but can't seem to get it started on stage 2

**Comment by EvgeniyKorepov** [comment]
Show MinerPro settings (screenshot rig adding) and the command line for starting the Excavator

**Comment by fouriedavid** [comment]
![untitled](https://user-images.githubusercontent.com/37958879/38191615-be10a78c-3669-11e8-8c3d-d7d417d03f3a.jpg)
![untitled2](https://user-images.githubusercontent.com/37958879/38191616-be4e942a-3669-11e8-8350-f483b2c48fba.jpg)
![untitled3](https://user-images.githubusercontent.com/37958879/38191618-be8b0824-3669-11e8-900b-ccd16d6414f7.jpg)

Here are the screenshots

**Comment by EvgeniyKorepov** [comment]
@fouriedavid You run Excavator with API over HTTP, but try to connect to it via the TCP.
Read the section https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash/blob/master/README.md#PrepareExcavator

Use this config https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash/blob/master/ExcavatorServer.json and this start file https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash/blob/master/%23start.cmd

**Comment by fouriedavid** [comment]
ok tried that got this
![untitled4](https://user-images.githubusercontent.com/37958879/38193413-3f9dfa4a-3672-11e8-84cf-e47050101a89.jpg)

**Comment by fouriedavid** [comment]
![untitled5](https://user-images.githubusercontent.com/37958879/38194122-e4bc579e-3675-11e8-8cc1-482cec5238bd.jpg)

ok got that sorted but still error Excavator not connected

**Comment by EvgeniyKorepov** [comment]
Check start.cmd file
![image](https://user-images.githubusercontent.com/35364901/38196125-eddfa754-3689-11e8-95e8-7b2f30700e65.png)

**Comment by fouriedavid** [comment]
ok I changed it does this look better 
![untitled6](https://user-images.githubusercontent.com/37958879/38196245-2cbca830-3682-11e8-81a6-75dcabe42eaa.jpg)

sorry for bothering u so much

**Comment by fouriedavid** [comment]
ok got it this far can u help me get it running correctly
![untitled7](https://user-images.githubusercontent.com/37958879/38201270-fdb8c9a4-3697-11e8-9e2c-b10d633e4a9d.jpg)
 plz 
It doesn't want to bench or mine

**Comment by EvgeniyKorepov** [comment]
I highlighted the error with the color. The token in the executable file and in the settings of the Rig should be the same. This is the password for access. 
![image](https://user-images.githubusercontent.com/35364901/38203468-fc06c9f2-36a7-11e8-9743-797ee4b9a49d.png)

**Comment by fouriedavid** [comment]
Ok will try that thanks

**Comment by fouriedavid** [comment]
Its running fine now thanks for all the help
