### ISSUE TITLE
Help with configuration

### ISSUE THREAD

**Issue by Rsalvador2008** [EvgeniyKorepov/MinerPro-for-NiceHash#2]
Hello, can you please give better instruction's how to configure the miner?
i don't know how to configure the stage 2 excavator settings, I am used to the nicehash miner that is very easy to setup, but I would like to try this one as well.

thanks

**Comment by EvgeniyKorepov** [comment]
Download the archive [ExcavatorServer_bat_and_config.zip](https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash/blob/master/ExcavatorServer_bat_and_config.zip) and unpack it to the folder with the excavator. Run the file #start.bat. All is ready. 

In the application, enter the IP address (Host) of the computer where the excavator is running, or 127.0.0.1 if on the same computer.

**Comment by Rsalvador2008** [comment]
Tanks alreay working

Os melhores cumprimentos

Ricardo Salvador

________________________________
