### ISSUE TITLE
Benckmarking Mode / Mining Mode

### ISSUE THREAD

**Issue by SLO-onca** [EvgeniyKorepov/MinerPro-for-NiceHash#5]
Not immediately visually obvious how to benchmark or that you are in one mode or another.

Provide better visual feedback as to which mode you are in 'Benchmark Mode' or 'Mining Mode'

**Comment by EvgeniyKorepov** [comment]
I agree. I'm still thinking about visualization. While there is only the inscription on the button and the color of the rig on the left

Automatic operation mode:
<img width="173" alt="screenshot006" src="https://user-images.githubusercontent.com/35364901/35763493-a2eaafd0-08be-11e8-81c0-92d2e5c78d24.PNG">

Benchmark mode:
<img width="177" alt="screenshot007" src="https://user-images.githubusercontent.com/35364901/35763497-b3316ae6-08be-11e8-9a14-3472cfd4c0b9.PNG">
