### ISSUE TITLE
Labour intensive to benchmark.

### ISSUE THREAD

**Issue by SLO-onca** [EvgeniyKorepov/MinerPro-for-NiceHash#6]
You have to benchmark each algorithm individually.

Allow multiselect algo's and benchmark each automatically.

Take average of hash rate and power metrics to capture automatically rather than waiting and clicking to capture.

**Comment by EvgeniyKorepov** [comment]
Running the benchmark operation is thin and is rarely performed. It is better to be able to fine-tune each algorithm. Find the parameters of the GPUs and the parameters of the worker (in the next version).  Batch benchmark in NHML and NHM2 delays more problems than good.
