### ISSUE TITLE
Labour intensive to Set TDP, Core and Mem Deltas

### ISSUE THREAD

**Issue by SLO-onca** [EvgeniyKorepov/MinerPro-for-NiceHash#7]
Allow Multi-select on Algo's and allow setting all at once.

**Comment by EvgeniyKorepov** [comment]
You can always edit the configuration file of the rig (example MinerProForNicehash\rigs\node07_192.168.0.156_rig.json):
```
    "lyra2rev2": {
      "Enable": true,
      "Devices_TDP_CoreDelta_MemoryDelta": [95, 120, -500],
      "WorkerPerDevice": 1,
      "WorkerParameters": [],
      "Speed": 204858649.649848,
      "Power": 828
    },
```
Change the data in the row
"Devices_TDP_CoreDelta_MemoryDelta": [95, 120, -500],
and press Button "Reload rig from config file" - The next time you start the algorithm, apply the new parameters.

Multi-select on Algo's  - quite dangerous, different algorithms need different settings. In addition, the button "Apply GPUs setting" changes the current settings of the running GPUs.
