### ISSUE TITLE
UI feedback donation

### ISSUE THREAD

**Issue by SLO-onca** [EvgeniyKorepov/MinerPro-for-NiceHash#8]
For transparency:

1. Show total amount of BTC donated to date.
2. Show when donating BTC

**Comment by EvgeniyKorepov** [comment]
Good question. For more information, see the GUI logs:
```
06:19:22 Algorithm node07 Rig start neoscrypt
06:38:07 Rig node07 Dev fee start mining
06:38:07 Algorithm node07 Rig stop neoscrypt (worked 0:18:45)
06:38:07 Algorithm node07 Rig start neoscrypt
06:39:07 Rig node07 Dev fee stop mining
06:39:07 Algorithm node07 Rig stop neoscrypt (worked 0:01:00)
06:39:07 Algorithm node07 Rig start neoscrypt
```
and file logs (subfolder logs), search by "Dev fee start mining" and "Dev fee stop mining".

I will be very grateful for the verification, most of all I'm afraid to deceive users and exceed the size of Dev Fee

**Comment by SLO-onca** [comment]
No worries, just trying to make it obvious.
