### ISSUE TITLE
UI Feedback BTC / Currency

### ISSUE THREAD

**Issue by SLO-onca** [EvgeniyKorepov/MinerPro-for-NiceHash#9]
Show exchange current exchange rate that you are using for currency.

i.e. 1 BTC = 10883 CAD

**Comment by EvgeniyKorepov** [comment]
The exchange rate is taken from Nicehash. Here is the API link https://api.nicehash.com/api?method=nicehash.service.info. Also you can find a cached copy in the file
MinerProForNicehash\cache\service.info.json

({"USD": "8213.7","coin": "BTC"}) * ("CAD": 1.2317) = 10116,81429

**Comment by EvgeniyKorepov** [comment]
In next version :
![image](https://user-images.githubusercontent.com/35364901/35769058-546e7dde-0916-11e8-9edb-35b81fab4f83.png)
